In [6]:
import pandas as pd

In [7]:
attacks= pd.read_csv('attacks.csv', encoding='latin1')

In [8]:
pd.options.display.max_columns=30

In [9]:
attacks

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#aqui removemos todas as linhas que tÃªm todos os campos com NaN.

mascara = attacks.isna().sum(axis = 1) < 20
attacks=attacks.loc[mascara, : ]
attacks.tail(2)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ÂºN, 79ÂºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

In [11]:
#metemos tudo em minuscula e sem o esp. tal como deve ser.

attacks.columns = [c.lower() for c in attacks.columns]
attacks.columns = [c.replace(' ','_') for c in attacks.columns]

In [12]:
attacks.columns

Index(['case_number', 'date', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'sex_', 'age', 'injury', 'fatal_(y/n)', 'time',
       'species_', 'investigator_or_source', 'pdf', 'href_formula', 'href',
       'case_number.1', 'case_number.2', 'original_order', 'unnamed:_22',
       'unnamed:_23'],
      dtype='object')

In [13]:
attacks.head(2)

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,unnamed:_22,unnamed:_23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN

In [14]:
attacks['unnamed:_23'].unique()
#ver o que nÃ£o Ã© NaN

array([nan, 'Teramo', 'change filename'], dtype=object)

In [15]:
attacks['unnamed:_23'].isna().value_counts()
#confirmar que a maioria sÃ£o NaN

True     6300
False       2
Name: unnamed:_23, dtype: int64

In [16]:
attacks['unnamed:_23'].unique()
#ver o que nÃ£o Ã© NaN

array([nan, 'Teramo', 'change filename'], dtype=object)

In [17]:
attacks[['unnamed:_22','unnamed:_23' ]].isnull().value_counts()
#confirmar que a maioria sÃ£o NaN

unnamed:_22  unnamed:_23
True         True           6299
             False             2
False        True              1
dtype: int64

In [18]:
attacks=attacks.drop(columns=['unnamed:_22','unnamed:_23' ])
#tirar as duas colunas

In [19]:
attacks

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ÂºN, 79ÂºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0

In [20]:
attacks['fatal_(y/n)'].unique()

array(['N', 'Y', nan, 'M', 'UNKNOWN', '2017', ' N', 'N ', 'y'],
      dtype=object)

In [21]:
attacks.loc[attacks['fatal_(y/n)'].isna() ]

#mortes sobre as quais nao sabemos se a pessoa morreu ou nÃ£o

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0
76,2017.10.01,01-Oct-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,31,FATAL,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01,6227.0
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b,6224.0
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,25,"FATAL, but death was probably due to drowning",NaN,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b,6219.0
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,CastellÃ³n,Grao de Moncofa,Swimming,female,F,11,Lacerations to left foot,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b,6205.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6147,1767.00.00,1767,1767.0,Invalid,FRANCE,CÃ´te d'Azur,St. Tropez,Bathing,Samuel Matthews,M,NaN,Lacerations to arm & leg,NaN,NaN,Description of shark does not ring true,NaN,1767.00.00-Matthews.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1767.00.00,1767.00.00,156.0
6157,1733.00.00,1733,1733.0,Invalid,ICELAND,Bardestrand,Talkknefiord,NaN,NaN,NaN,NaN,"Partial hominid remains recovered from shark, ...",NaN,NaN,Shark involvement prior to death unconfirmed,E. Olafsen,1733.00.00-Iceland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1733.00.00,1733.00.00,146.0
6158,1723.00.00,1723,1723.0,Unprovoked,ROATAN,NaN,NaN,NaN,Philip Ashton,M,NaN,Struck on thigh,NaN,NaN,NaN,"C.Moore, GSAF",1730.00.00-Ashton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1723.00.00,1723.00.00,145.0
6164,1642.00.00.b,Late 1600s Reported 1728,1642.0,Invalid,GUINEA,NaN,NaN,Went overboard,crew member of the Nieuwstadt,M,NaN,FATAL,NaN,NaN,Questionable,"History of the Pyrates, by D. Defoe, Vol. 2, p.28",1642.00.00.b-Nieuwstadt.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1642.00.00.b,1642.00.00.b,139.0
6232,ND.0081,"No date, Before 1963",0.0,Invalid,USA,Hawaii,"Portlock, Oahu",Diving,Val Valentine,M,NaN,A 4.3 m [14'] shark made threat display. No in...,NaN,NaN,Invalid,B. Sojka & D. Lloyd,ND-0081-Valentine.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0081,ND.0081,71.0

In [22]:
def reduzir(x):
    if x == ' N' or x == 'N ' or x == 'M' or x == '2017':
        return 'N'
    elif x == 'y':
        return 'Y'
    else: 
        return x

attacks['fatal_(y/n)_ze'] = attacks['fatal_(y/n)'].apply(reduzir)

In [23]:
attacks['fatal_(y/n)_ze'].unique()

array(['N', 'Y', nan, 'UNKNOWN'], dtype=object)

In [24]:
attacks.loc[attacks['fatal_(y/n)_ze'].isna()]

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0,NaN
76,2017.10.01,01-Oct-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,31,FATAL,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01,6227.0,NaN
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,USA,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b,6224.0,NaN
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,SOUTH AFRICA,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,25,"FATAL, but death was probably due to drowning",NaN,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b,6219.0,NaN
98,2017.08.26.b,26-Aug-2017,2017.0,Invalid,SPAIN,CastellÃ³n,Grao de Moncofa,Swimming,female,F,11,Lacerations to left foot,NaN,Midday,Shark involvement questionable,"El Periodico Mediterraneo, 8/27/2017",2017.08.26.b-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b,2017.08.26.b,6205.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6147,1767.00.00,1767,1767.0,Invalid,FRANCE,CÃ´te d'Azur,St. Tropez,Bathing,Samuel Matthews,M,NaN,Lacerations to arm & leg,NaN,NaN,Description of shark does not ring true,NaN,1767.00.00-Matthews.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1767.00.00,1767.00.00,156.0,NaN
6157,1733.00.00,1733,1733.0,Invalid,ICELAND,Bardestrand,Talkknefiord,NaN,NaN,NaN,NaN,"Partial hominid remains recovered from shark, ...",NaN,NaN,Shark involvement prior to death unconfirmed,E. Olafsen,1733.00.00-Iceland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1733.00.00,1733.00.00,146.0,NaN
6158,1723.00.00,1723,1723.0,Unprovoked,ROATAN,NaN,NaN,NaN,Philip Ashton,M,NaN,Struck on thigh,NaN,NaN,NaN,"C.Moore, GSAF",1730.00.00-Ashton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1723.00.00,1723.00.00,145.0,NaN
6164,1642.00.00.b,Late 1600s Reported 1728,1642.0,Invalid,GUINEA,NaN,NaN,Went overboard,crew member of the Nieuwstadt,M,NaN,FATAL,NaN,NaN,Questionable,"History of the Pyrates, by D. Defoe, Vol. 2, p.28",1642.00.00.b-Nieuwstadt.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1642.00.00.b,1642.00.00.b,139.0,NaN
6232,ND.0081,"No date, Before 1963",0.0,Invalid,USA,Hawaii,"Portlock, Oahu",Diving,Val Valentine,M,NaN,A 4.3 m [14'] shark made threat display. No in...,NaN,NaN,Invalid,B. Sojka & D. Lloyd,ND-0081-Valentine.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0081,ND.0081,71.0,NaN

In [25]:
#attacks.drop('fatal_(y/n)_ze',axis= 1)

In [26]:
attacks_fatal= attacks.loc[(attacks['fatal_(y/n)_ze'] == 'Y') | (attacks['fatal_(y/n)_ze'] ==  'N')]

In [27]:
attacks_fatal['fatal_(y/n)_ze'].unique()

array(['N', 'Y'], dtype=object)

In [28]:
attacks_fatal['sex_'].unique()

array(['F', 'M', nan, 'M ', 'lli', 'N', '.'], dtype=object)

In [29]:
#attacks_fatal.loc[attacks_Fatal['sex_'] == 'lli']

#attacks_fatal.loc[attacks_Fatal['sex_'] == 'M ']

#attacks_fatal.loc[attacks_Fatal['sex_'] == '.']

#attacks_fatal.loc[attacks_fatal['sex_'].isna()]

In [30]:

attacks_fatal['sex_'][1624] ='M'
attacks_fatal['sex_'][563] ='M'
attacks_fatal['sex_'][6131] ='M'
attacks_fatal['sex_'][1587]='M'

#attacks.loc[4938, : ]

C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\jmcac\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3331: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [31]:
import numpy as np

In [32]:
attacks_fatal['sex_'][4938] = np.nan
attacks_fatal['sex_'][5437] = np.nan

#atribuimos nan a estes casos visto nao sabermos se sÃ£o homem

C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\jmcac\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3331: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [33]:
 attacks_fatal = attacks_fatal.loc[(attacks_fatal['sex_'] == 'M') | (attacks_fatal['sex_'] == 'F')]

In [34]:
attacks_fatal['sex_'].unique()

array(['F', 'M'], dtype=object)

In [35]:
pd.set_option('display.max_colwidth', -1)

#mostrar o tamanho total das colunas

C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  """Entry point for launching an IPython kernel.

In [36]:
#ficou dividido em homem e mulher. 
attacks_fatal.head()

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and paddle damaged",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf,2018.06.25,2018.06.25,6303.0,N
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,2018.06.18,2018.06.18,6302.0,N
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.09-Denges.pdf,2018.06.09,2018.06.09,6301.0,N
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.08-Arrawarra.pdf,2018.06.08,2018.06.08,6300.0,N
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.04-Ramos.pdf,2018.06.04,2018.06.04,6299.0,N

In [37]:
attacks_fatal.loc[attacks_fatal['age'].isna()]

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.08-Arrawarra.pdf,2018.06.08,2018.06.08,6300.0,N
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.04-Ramos.pdf,2018.06.04,2018.06.04,6299.0,N
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris,M,NaN,"No injury, board bitten",N,NaN,NaN,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.03.b-FlatRock.pdf,2018.06.03.b,2018.06.03.b,6298.0,N
15,2018.05.12,12-May-2018,2018.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,"Nahoon Beach, East London",Surfing,male,M,NaN,"Minor injury, marks on board",N,11h00,NaN,"B.Jacob, Dispatch Live, 5/12/2018",2018.05.12-EastLondon.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.05.12-EastLondon.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.05.12-EastLondon.pdf,2018.05.12,2018.05.12,6288.0,N
16,2018.05.09,09-May-2018,2018.0,Questionable,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,male,M,NaN,"No injury, surfboard damaged",N,10h30,Shark involvement not confirmed,"B. Myatt, GSAF",2018.05.09-SharpesBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.05.09-SharpesBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.05.09-SharpesBeach.pdf,2018.05.09,2018.05.09,6287.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6296,ND.0006,Before 1906,0.0,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,NaN,FATAL,Y,NaN,Said to involve a grey nurse shark that leapt out of the water and seized the boy but species identification is questionable,"L. Becke in New York Sun, 9/9/1906; L. Schultz & M. Malin, p.523",ND-0006-ArabBoy-Prymount.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0006-ArabBoy-Prymount.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0006-ArabBoy-Prymount.pdf,ND.0006,ND.0006,7.0,Y
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0005-RoebuckBay.pdf,ND.0005,ND.0005,6.0,Y
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0004-Ahmun.pdf,ND.0004,ND.0004,5.0,Y
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0003-Ocracoke_1900-1905.pdf,ND.0003,ND.0003,4.0,Y
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ÂºN, 79ÂºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0002-JulesPatterson.pdf,ND.0002,ND.0002,3.0,Y

In [38]:
attacks_fatal['age'].count()

#quantos na idade nÃ£o sÃ£o NaN

3201

In [39]:
attacks_fatal.shape

#tamanho em nan sÃ³ com homem e mulher

(5234, 23)

In [40]:
attacks.shape

#tamanho em nan sÃ³ com homem e mulher

(6302, 23)

In [41]:
attacks_fatal['age'].unique()

array(['57', '11', '48', nan, '18', '52', '15', '12', '32', '10', '21',
       '34', '30', '60', '33', '29', '54', '41', '37', '56', '19', '25',
       '69', '38', '55', '35', '46', '45', '14', '40s', '28', '20', '24',
       '26', '49', '22', '7', '31', '17', '40', '13', '42', '3', '50',
       '16', '82', '73', '20s', '51', '39', '58', 'Teen', '47', '61',
       '65', '36', '66', '43', '60s', '9', '72', '59', '6', '64', '23',
       '71', '44', '27', '62', '68', '63', '70', '18 months', '53', '30s',
       '50s', '8', 'teen', '77', '74', '28 & 26', '5', '86', '18 or 20',
       '12 or 13', '46 & 34', '28, 23 & 30', 'Teens', '84', '\xa0 ', ' ',
       '30 or 36', '6Â½', '21 & ?', '33 or 37', 'mid-30s', ' 30',
       '7      &    31', ' 28', '20?', "60's", '32 & 30', '87', 'Elderly',
       '75', '74 ', '45 ', '21 or 26', '20 ', '>50', '18 to 22', 'adult',
       '9 months', '25 to 35', '23 & 26', '1', '(adult)', '33 & 37',
       '25 or 28', '30 & 32', '17 & 35', 'X', '"middle-age"', '13 or 18',
       '33 & 26', ' 43', '81', '"young"', '7 or 8', '78', '8 or 10', 'F',
       'Both 11', '9 or 10', 'young', '36 & 23', '  ', 'A.M.',
       '?    &   14', '10 or 12', '31 or 33', '2Â½', '13 or 14'],
      dtype=object)

In [42]:
e = attacks_fatal[attacks_fatal['age'].str.match('\d+ & .*') == True]
e = e.append(e)

In [43]:
e['age'].count()

20

In [44]:
idades = (28,46,21,32,23,33,30,17,33,36,26,34,'?',30,26,37,32,35,26,23)

In [45]:
e['age'] = idades

In [46]:
e['age']

698     28
1506    46
1925    21
2511    32
3742    23
3880    33
4009    30
4039    17
4118    33
4999    36
698     26
1506    34
1925    ?
2511    30
3742    26
3880    37
4009    32
4039    35
4118    26
4999    23
Name: age, dtype: object

In [47]:
lista_apagar=attacks_fatal[attacks_fatal['age'].str.match('\d+ & .*') == True].index.values.tolist() 
lista_apagar

[698, 1506, 1925, 2511, 3742, 3880, 4009, 4039, 4118, 4999]

In [48]:
attacks_fatal = attacks_fatal.drop(lista_apagar,axis= 0)

In [49]:
#confirmar que ficou apagado
#a coluna 1506 dÃ¡ erro
#a coluna 1506  nÃ£o dÃ¡ erro

attacks_fatal.loc[698, : ]
#attacks_fatal.loc[1507, : ]

KeyError: 698

In [50]:
attacks_fatal = attacks_fatal.append(e)

In [51]:
attacks_fatal.loc[1506, : ]

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze
1506,2006.01.28.R,Reported 28-Jan-2006,2006.0,Boating,ATLANTIC OCEAN,300 miles from Antigua,NaN,Competing in the Woodvale Atlantic Rowing Race,"Mayabrit, an ocean rowing boat. Occupants: Andrew Barnett & J.C.S. Brendana",M,46,No injury to occupants; shark rammed boat repeatedly,N,NaN,12' shark,"N. Bevan, icwales.icnetwork.co.uk, 1/28/2006",2006.01.28.R-Mayabrit.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.28.R-Mayabrit.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.28.R-Mayabrit.pdf,2006.01.28.R,2006.01.28.R,4797.0,N
1506,2006.01.28.R,Reported 28-Jan-2006,2006.0,Boating,ATLANTIC OCEAN,300 miles from Antigua,NaN,Competing in the Woodvale Atlantic Rowing Race,"Mayabrit, an ocean rowing boat. Occupants: Andrew Barnett & J.C.S. Brendana",M,34,No injury to occupants; shark rammed boat repeatedly,N,NaN,12' shark,"N. Bevan, icwales.icnetwork.co.uk, 1/28/2006",2006.01.28.R-Mayabrit.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.28.R-Mayabrit.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.28.R-Mayabrit.pdf,2006.01.28.R,2006.01.28.R,4797.0,N

In [52]:
attacks_fatal['age'].unique()

array(['57', '11', '48', nan, '18', '52', '15', '12', '32', '10', '21',
       '34', '30', '60', '33', '29', '54', '41', '37', '56', '19', '25',
       '69', '38', '55', '35', '46', '45', '14', '40s', '28', '20', '24',
       '26', '49', '22', '7', '31', '17', '40', '13', '42', '3', '50',
       '16', '82', '73', '20s', '51', '39', '58', 'Teen', '47', '61',
       '65', '36', '66', '43', '60s', '9', '72', '59', '6', '64', '23',
       '71', '44', '27', '62', '68', '63', '70', '18 months', '53', '30s',
       '50s', '8', 'teen', '77', '74', '5', '86', '18 or 20', '12 or 13',
       '28, 23 & 30', 'Teens', '84', '\xa0 ', ' ', '30 or 36', '6Â½',
       '33 or 37', 'mid-30s', ' 30', '7      &    31', ' 28', '20?',
       "60's", '87', 'Elderly', '75', '74 ', '45 ', '21 or 26', '20 ',
       '>50', '18 to 22', 'adult', '9 months', '25 to 35', '1', '(adult)',
       '25 or 28', 'X', '"middle-age"', '13 or 18', ' 43', '81',
       '"young"', '7 or 8', '78', '8 or 10', 'F', 'Both 11', '9 or 10',
       'young', '  ', 'A.M.', '?    &   14', '10 or 12', '31 or 33', '2Â½',
       '13 or 14', 28, 46, 21, 32, 23, 33, 30, 17, 36, 26, 34, '?', 37,
       35], dtype=object)

In [53]:
ou = attacks_fatal[attacks_fatal['age'].str.match('\d+ or .*') == True]

In [54]:
ou['age']

1325    18 or 20
1436    12 or 13
1881    30 or 36
1949    33 or 37
3187    21 or 26
3933    25 or 28
4075    13 or 18
4489    7 or 8
4629    8 or 10
4818    9 or 10
5312    10 or 12
5483    31 or 33
6063    7 or 8
6265    13 or 14
Name: age, dtype: object

In [55]:
media_idades = (19, 12, 33, 35, 24, 26, 16, 8, 9, 9, 11, 32, 8, 14)
#fazemos as medias das idades e colocamos de novo. na linha abaixo

In [56]:
ou['age'] = media_idades

C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [57]:
ou['age']

1325    19
1436    12
1881    33
1949    35
3187    24
3933    26
4075    16
4489    8
4629    9
4818    9
5312    11
5483    32
6063    8
6265    14
Name: age, dtype: int32

In [58]:
#lista com os indices que queremos apagar.

lista_apagar_2 = attacks_fatal[attacks_fatal['age'].str.match('\d+ or .*') == True].index.values.tolist() 

lista_apagar_2

[1325,
 1436,
 1881,
 1949,
 3187,
 3933,
 4075,
 4489,
 4629,
 4818,
 5312,
 5483,
 6063,
 6265]

In [59]:
#aqui apagamos as linhas que utilizamos para fazer a lista ou para mais em baixo as colocarmos de novo.
attacks_fatal = attacks_fatal.drop(lista_apagar_2,axis= 0)

In [60]:
#podemos confirmar que a linha 1325 nao aparece porque a apagamos mas que a outra sim
# 
#attacks_fatal.loc[1324, : ]
#attacks_fatal.loc[1325, : ]

In [61]:
attacks_fatal = attacks_fatal.append(ou)

In [62]:
attacks_fatal.loc[1325, : ]

#aqui confirmamos que foi inserida de novo.

case_number               2007.09.27.a
date                      27-Sep-2007
year                      2007
type                      Unprovoked
country                   EGYPT
area                      Red Sea
location                  Daedalus ReefÂ
activity                  Swimming
name                      Kristina Aleksandrova
sex_                      F
age                       19
injury                    Severe lacerations to lower left leg, ankle and foot
fatal_(y/n)               N
time                      07h00
species_                  Oceanic whitetip sharks were in the vicinity
investigator_or_source    E. Ritter & Y. Sobolev, GSAF; M. Salem
pdf                       2007.09.27.a-Aleksandrova.pdf
href_formula              http://sharkattackfile.net/spreadsheets/pdf_directory/2007.09.27.a-Aleksandrova.pdf
href                      http://sharkattackfile.net/spreadsheets/pdf_directory/2007.09.27.a-Aleksandrova.pdf
case_number.1             2007.09.27.a
case_number.2             2007.09.27.a
original_order            4978
fatal_(y/n)_ze            N
Name: 1325, dtype: object

In [63]:
attacks_fatal['age'].unique()

array(['57', '11', '48', nan, '18', '52', '15', '12', '32', '10', '21',
       '34', '30', '60', '33', '29', '54', '41', '37', '56', '19', '25',
       '69', '38', '55', '35', '46', '45', '14', '40s', '28', '20', '24',
       '26', '49', '22', '7', '31', '17', '40', '13', '42', '3', '50',
       '16', '82', '73', '20s', '51', '39', '58', 'Teen', '47', '61',
       '65', '36', '66', '43', '60s', '9', '72', '59', '6', '64', '23',
       '71', '44', '27', '62', '68', '63', '70', '18 months', '53', '30s',
       '50s', '8', 'teen', '77', '74', '5', '86', '28, 23 & 30', 'Teens',
       '84', '\xa0 ', ' ', '6Â½', 'mid-30s', ' 30', '7      &    31',
       ' 28', '20?', "60's", '87', 'Elderly', '75', '74 ', '45 ', '20 ',
       '>50', '18 to 22', 'adult', '9 months', '25 to 35', '1', '(adult)',
       'X', '"middle-age"', ' 43', '81', '"young"', '78', 'F', 'Both 11',
       'young', '  ', 'A.M.', '?    &   14', '2Â½', 28, 46, 21, 32, 23, 33,
       30, 17, 36, 26, 34, '?', 37, 35, 19, 12, 24, 16, 8, 9, 11, 14],
      dtype=object)

In [64]:
def corrigir(x):
    if x == '30s':
        return 35
    elif x == '40s':
        return 45
    elif x == '50s':
        return 55
    elif x == '20s':
        return 25
    elif x == '20s':
        return 65
    else: 
        return x

attacks_fatal['idade'] = attacks_fatal['age'].apply(corrigir)

In [65]:

attacks_fatal['idade'].unique()

array(['57', '11', '48', nan, '18', '52', '15', '12', '32', '10', '21',
       '34', '30', '60', '33', '29', '54', '41', '37', '56', '19', '25',
       '69', '38', '55', '35', '46', '45', '14', 45, '28', '20', '24',
       '26', '49', '22', '7', '31', '17', '40', '13', '42', '3', '50',
       '16', '82', '73', 25, '51', '39', '58', 'Teen', '47', '61', '65',
       '36', '66', '43', '60s', '9', '72', '59', '6', '64', '23', '71',
       '44', '27', '62', '68', '63', '70', '18 months', '53', 35, 55, '8',
       'teen', '77', '74', '5', '86', '28, 23 & 30', 'Teens', '84',
       '\xa0 ', ' ', '6Â½', 'mid-30s', ' 30', '7      &    31', ' 28',
       '20?', "60's", '87', 'Elderly', '75', '74 ', '45 ', '20 ', '>50',
       '18 to 22', 'adult', '9 months', '25 to 35', '1', '(adult)', 'X',
       '"middle-age"', ' 43', '81', '"young"', '78', 'F', 'Both 11',
       'young', '  ', 'A.M.', '?    &   14', '2Â½', 28, 46, 21, 32, 23, 33,
       30, 17, 36, 26, 34, '?', 37, 19, 12, 24, 16, 8, 9, 11, 14],
      dtype=object)

In [66]:
attacks_fatal.loc[attacks_fatal['idade'] == '6Â½']

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze,idade
1901,2001.09.15.b,15-Sep-2001,2001.0,Unprovoked,USA,Florida,A quarter mile north of Fort Pierce Inlet,Boogie boarding,Cory Hock,M,6Â½,"2 lacerations on lower back, punctures on buttock",N,15h00,2' to 3.5' shark,"G. Hock, M. Levine, GSAF; Orlando Sentinel, 9/18/2001, p.D2",2001.09.15.b-Hock.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2001.09.15.b-Hock.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2001.09.15.b-Hock.pdf,2001.09.15.b,2001.09.15.b,4402.0,N,6Â½

In [67]:

attacks_fatal['idade'][1901] = '6'
attacks_fatal['idade'][3546] = '1'
attacks_fatal['idade'][1955] = '35'

C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [68]:
def nao_zero(x):
     if x == 'young' or x == 'Elderly' or x == 'adult' or x == 'A.M.' or x == '  ' or x == '"young"' or x == '\xa0 ' or x == ' ' : 
            return np.nan
     elif x  == '(adult)'  or x == "young" or x == 'X' or x == 'F' or x == '?' or x == '>50' or x == '(adult)':
        return np.nan
     else:
        return x

attacks_fatal['idade'] = attacks_fatal['idade'].apply(nao_zero)

In [69]:
attacks_fatal[attacks_fatal['idade'] == '(adult)'] = np.nan

In [70]:
attacks_fatal['idade'].unique()

array(['57', '11', '48', nan, '18', '52', '15', '12', '32', '10', '21',
       '34', '30', '60', '33', '29', '54', '41', '37', '56', '19', '25',
       '69', '38', '55', '35', '46', '45', '14', 45, '28', '20', '24',
       '26', '49', '22', '7', '31', '17', '40', '13', '42', '3', '50',
       '16', '82', '73', 25, '51', '39', '58', 'Teen', '47', '61', '65',
       '36', '66', '43', '60s', '9', '72', '59', '6', '64', '23', '71',
       '44', '27', '62', '68', '63', '70', '18 months', '53', 35, 55, '8',
       'teen', '77', '74', '5', '86', '28, 23 & 30', 'Teens', '84', ' 30',
       '7      &    31', ' 28', '20?', "60's", '87', '75', '74 ', '45 ',
       '20 ', '18 to 22', '1', '25 to 35', '"middle-age"', ' 43', '81',
       '78', 'Both 11', '?    &   14', '2Â½', 28, 46, 21, 32, 23, 33, 30,
       17, 36, 26, 34, 37, 19, 12, 24, 16, 8, 9, 11, 14], dtype=object)

In [71]:
attacks_fatal[attacks_fatal['idade'] == '20?'].index
attacks_fatal[attacks_fatal['idade'] == '60\'s'].index
attacks_fatal[attacks_fatal['idade'] == '2Â½'].index

Int64Index([6002], dtype='int64')

In [72]:
attacks_fatal['idade'] [5181] = 14
attacks_fatal['idade'] [2441] = 25
attacks_fatal['idade'] [2496] = 65
attacks_fatal['idade'] [6002] = 2

C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [73]:
attacks_fatal[attacks_fatal['idade'] == '7      &    31']

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze,idade
2422,1994.09.11.R,Reported 11-Sep-1994,1994.0,Sea Disaster,USA,Florida,Florida Straits,Adrift on refugee raft,2 Cuban brothers,M,7 & 31,FATAL,Y,NaN,NaN,"Sunday Herald Sun, 9/11/1994, p.25",1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1994.09.11.R-CubanRefugees.pdf,1994.09.11.R,1994.09.11.R,3881.0,Y,7 & 31

In [74]:
linha_2422 = attacks_fatal[attacks_fatal['idade'] == '7      &    31']

In [75]:
linha_2422 = linha_2422.append(linha_2422)

In [76]:
idade_linha_2422 = (7,31)

In [77]:
linha_2422['idade'] = idade_linha_2422

In [78]:
linha_2422

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze,idade
2422,1994.09.11.R,Reported 11-Sep-1994,1994.0,Sea Disaster,USA,Florida,Florida Straits,Adrift on refugee raft,2 Cuban brothers,M,7 & 31,FATAL,Y,NaN,NaN,"Sunday Herald Sun, 9/11/1994, p.25",1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1994.09.11.R-CubanRefugees.pdf,1994.09.11.R,1994.09.11.R,3881.0,Y,7
2422,1994.09.11.R,Reported 11-Sep-1994,1994.0,Sea Disaster,USA,Florida,Florida Straits,Adrift on refugee raft,2 Cuban brothers,M,7 & 31,FATAL,Y,NaN,NaN,"Sunday Herald Sun, 9/11/1994, p.25",1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1994.09.11.R-CubanRefugees.pdf,1994.09.11.R,1994.09.11.R,3881.0,Y,31

In [79]:
attacks_fatal = attacks_fatal.drop(2422,axis= 0)

In [80]:
attacks_fatal = attacks_fatal.append(linha_2422)

In [81]:
attacks_fatal[attacks_fatal['age'] == '7      &    31']

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze,idade
2422,1994.09.11.R,Reported 11-Sep-1994,1994.0,Sea Disaster,USA,Florida,Florida Straits,Adrift on refugee raft,2 Cuban brothers,M,7 & 31,FATAL,Y,NaN,NaN,"Sunday Herald Sun, 9/11/1994, p.25",1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1994.09.11.R-CubanRefugees.pdf,1994.09.11.R,1994.09.11.R,3881.0,Y,7
2422,1994.09.11.R,Reported 11-Sep-1994,1994.0,Sea Disaster,USA,Florida,Florida Straits,Adrift on refugee raft,2 Cuban brothers,M,7 & 31,FATAL,Y,NaN,NaN,"Sunday Herald Sun, 9/11/1994, p.25",1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1994.09.11.R-CubanRefugees.pdf,1994.09.11.R,1994.09.11.R,3881.0,Y,31

In [82]:
vinte_23_trinta = attacks_fatal[attacks_fatal['idade'] == '28, 23 & 30']

vinte_23 = attacks_fatal[attacks_fatal['idade'] == '28, 23 & 30']

In [88]:
vinte_23_trinta = vinte_23_trinta.append(vinte_23)

In [89]:
vinte_23_trinta

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze,idade
1508,2006.01.23,23-Jan-2006,2006.0,Boating,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sally Kettle, Claire Mills & Sue McMillan",F,"28, 23 & 30","No injury to occupants; a shark, accidentally caught in a line, threatened to rip out the transom",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,2006.01.23,2006.01.23,4795.0,N,"28, 23 & 30"
1508,2006.01.23,23-Jan-2006,2006.0,Boating,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sally Kettle, Claire Mills & Sue McMillan",F,"28, 23 & 30","No injury to occupants; a shark, accidentally caught in a line, threatened to rip out the transom",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,2006.01.23,2006.01.23,4795.0,N,"28, 23 & 30"
1508,2006.01.23,23-Jan-2006,2006.0,Boating,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sally Kettle, Claire Mills & Sue McMillan",F,"28, 23 & 30","No injury to occupants; a shark, accidentally caught in a line, threatened to rip out the transom",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,2006.01.23,2006.01.23,4795.0,N,"28, 23 & 30"

In [90]:
lista_20_23_30 = (28,23,30)

In [91]:
vinte_23_trinta['idade'] = lista_20_23_30

In [92]:
vinte_23_trinta

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze,idade
1508,2006.01.23,23-Jan-2006,2006.0,Boating,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sally Kettle, Claire Mills & Sue McMillan",F,"28, 23 & 30","No injury to occupants; a shark, accidentally caught in a line, threatened to rip out the transom",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,2006.01.23,2006.01.23,4795.0,N,28
1508,2006.01.23,23-Jan-2006,2006.0,Boating,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sally Kettle, Claire Mills & Sue McMillan",F,"28, 23 & 30","No injury to occupants; a shark, accidentally caught in a line, threatened to rip out the transom",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,2006.01.23,2006.01.23,4795.0,N,23
1508,2006.01.23,23-Jan-2006,2006.0,Boating,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sally Kettle, Claire Mills & Sue McMillan",F,"28, 23 & 30","No injury to occupants; a shark, accidentally caught in a line, threatened to rip out the transom",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,2006.01.23,2006.01.23,4795.0,N,30

In [93]:
attacks_fatal=attacks_fatal.drop(1508, axis = 0)

In [95]:
#attacks_fatal.loc[1508]

In [96]:
attacks_fatal=attacks_fatal.append(vinte_23_trinta)

In [97]:
attacks_fatal.loc[1508]

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze,idade
1508,2006.01.23,23-Jan-2006,2006.0,Boating,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sally Kettle, Claire Mills & Sue McMillan",F,"28, 23 & 30","No injury to occupants; a shark, accidentally caught in a line, threatened to rip out the transom",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,2006.01.23,2006.01.23,4795.0,N,28
1508,2006.01.23,23-Jan-2006,2006.0,Boating,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sally Kettle, Claire Mills & Sue McMillan",F,"28, 23 & 30","No injury to occupants; a shark, accidentally caught in a line, threatened to rip out the transom",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,2006.01.23,2006.01.23,4795.0,N,23
1508,2006.01.23,23-Jan-2006,2006.0,Boating,ATLANTIC OCEAN,800 miles from land,NaN,Competing in the Woodvale Atlantic Rowing Race,"Rowgirls, an ocean rowing boat. Occupants: Sally Kettle, Claire Mills & Sue McMillan",F,"28, 23 & 30","No injury to occupants; a shark, accidentally caught in a line, threatened to rip out the transom",N,NaN,NaN,"Northants News, 1/25/2006",2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2006.01.23-Rowgirls.pdf,2006.01.23,2006.01.23,4795.0,N,30

In [98]:
attacks_fatal['idade'].unique()

array(['57', '11', '48', nan, '18', '52', '15', '12', '32', '10', '21',
       '34', '30', '60', '33', '29', '54', '41', '37', '56', '19', '25',
       '69', '38', '55', '35', '46', '45', '14', 45, '28', '20', '24',
       '26', '49', '22', '7', '31', '17', '40', '13', '42', '3', '50',
       '16', '82', '73', 25, '51', '39', '58', 'Teen', '47', '61', '65',
       '36', '66', '43', '60s', '9', '72', '59', '6', '64', '23', '71',
       '44', '27', '62', '68', '63', '70', '18 months', '53', 35, 55, '8',
       'teen', '77', '74', '5', '86', 'Teens', '84', ' 30', ' 28', 65,
       '87', '75', '74 ', '45 ', '20 ', '18 to 22', '1', '25 to 35',
       '"middle-age"', ' 43', '81', '78', 'Both 11', 14, 2, 28, 46, 21,
       32, 23, 33, 30, 17, 36, 26, 34, 37, 19, 12, 24, 16, 8, 9, 11, 7,
       31], dtype=object)

In [99]:
both_11 =attacks_fatal[attacks_fatal['idade'] == 'Both 11']

In [100]:
both_11 = both_11.append(both_11)

In [101]:
both_11

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze,idade
4801,1939.01.12,12-Jan-1939,1939.0,Unprovoked,AUSTRALIA,New South Wales,Clarence River,Scooping prawns,Earl Yager & Riley McLachlan,M,Both 11,No injury,N,NaN,7' shark,"G.P. Whitley, p.264",1939.01.12.R-ClarenceRiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1939.01.12.R-ClarenceRiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1939.01.12.R-ClarenceRiver.pdf,1939.01.12,1939.01.12,1502.0,N,Both 11
4801,1939.01.12,12-Jan-1939,1939.0,Unprovoked,AUSTRALIA,New South Wales,Clarence River,Scooping prawns,Earl Yager & Riley McLachlan,M,Both 11,No injury,N,NaN,7' shark,"G.P. Whitley, p.264",1939.01.12.R-ClarenceRiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1939.01.12.R-ClarenceRiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1939.01.12.R-ClarenceRiver.pdf,1939.01.12,1939.01.12,1502.0,N,Both 11

In [102]:
lista_11 = (11,11)
both_11['idade'] = lista_11

In [103]:
attacks_fatal=attacks_fatal.drop(4801, axis = 0)

In [104]:
attacks_fatal=attacks_fatal.append(both_11)

In [105]:
attacks_fatal.loc[4801]

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze,idade
4801,1939.01.12,12-Jan-1939,1939.0,Unprovoked,AUSTRALIA,New South Wales,Clarence River,Scooping prawns,Earl Yager & Riley McLachlan,M,Both 11,No injury,N,NaN,7' shark,"G.P. Whitley, p.264",1939.01.12.R-ClarenceRiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1939.01.12.R-ClarenceRiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1939.01.12.R-ClarenceRiver.pdf,1939.01.12,1939.01.12,1502.0,N,11
4801,1939.01.12,12-Jan-1939,1939.0,Unprovoked,AUSTRALIA,New South Wales,Clarence River,Scooping prawns,Earl Yager & Riley McLachlan,M,Both 11,No injury,N,NaN,7' shark,"G.P. Whitley, p.264",1939.01.12.R-ClarenceRiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1939.01.12.R-ClarenceRiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1939.01.12.R-ClarenceRiver.pdf,1939.01.12,1939.01.12,1502.0,N,11

In [113]:
attacks_fatal[attacks_fatal['idade'] == '18 months'].index
attacks_fatal[attacks_fatal['idade'] == 'Teens'].index
attacks_fatal[attacks_fatal['idade'] == '"middle-age"'].index
Teen = list(attacks_fatal[attacks_fatal['idade'] == 'Teen'].index)
teen = list(attacks_fatal[attacks_fatal['idade'] == 'teen'].index)

In [119]:
attacks_fatal[attacks_fatal['idade'] == '"middle-age"'].index

Int64Index([4064], dtype='int64')

In [120]:
attacks_fatal=attacks_fatal.drop(4064, axis = 0)
attacks_fatal=attacks_fatal.drop(445, axis = 0)
attacks_fatal=attacks_fatal.drop(1590, axis = 0)
attacks_fatal=attacks_fatal.drop(teen, axis = 0)
attacks_fatal=attacks_fatal.drop(Teen, axis = 0)

KeyError: '[445] not found in axis'

In [116]:
#attacks_fatal[attacks_fatal['idade'] == '18 to 22'].index
#attacks_fatal[attacks_fatal['idade'] == '60s'].index
#attacks_fatal[attacks_fatal['idade'] == '25 to 35'].index

In [117]:

attacks_fatal['idade'][3375]= 20
attacks_fatal['idade'][219] = 60
attacks_fatal['idade'][3646] = 30

C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\jmcac\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [121]:
attacks_fatal['idade'].unique()

array(['57', '11', '48', nan, '18', '52', '15', '12', '32', '10', '21',
       '34', '30', '60', '33', '29', '54', '41', '37', '56', '19', '25',
       '69', '38', '55', '35', '46', '45', '14', 45, '28', '20', '24',
       '26', '49', '22', '7', '31', '17', '40', '13', '42', '3', '50',
       '16', '82', '73', 25, '51', '39', '58', '47', '61', '65', '36',
       '66', '43', 60, '9', '72', '59', '6', '64', '23', '71', '44', '27',
       '62', '68', '63', '70', '53', 35, 55, '8', '77', '74', '5', '86',
       '84', ' 30', ' 28', 65, '87', '75', '74 ', '45 ', '20 ', 20, '1',
       30, ' 43', '81', '78', 14, 2, 28, 46, 21, 32, 23, 33, 17, 36, 26,
       34, 37, 19, 12, 24, 16, 8, 9, 11, 7, 31], dtype=object)

In [122]:
attacks_fatal[attacks_fatal['idade'] == '25 to 35']

Empty DataFrame
Columns: [case_number, date, year, type, country, area, location, activity, name, sex_, age, injury, fatal_(y/n), time, species_, investigator_or_source, pdf, href_formula, href, case_number.1, case_number.2, original_order, fatal_(y/n)_ze, idade]
Index: []

In [123]:
attacks_float= attacks_fatal.idade.astype('float64')

In [124]:
attacks_fatal['idade'] = attacks_float

In [125]:
attacks_fatal['idade'].dtypes ==  'float64'

True

In [126]:
attacks_fatal['idade'].unique()

array([57., 11., 48., nan, 18., 52., 15., 12., 32., 10., 21., 34., 30.,
       60., 33., 29., 54., 41., 37., 56., 19., 25., 69., 38., 55., 35.,
       46., 45., 14., 28., 20., 24., 26., 49., 22.,  7., 31., 17., 40.,
       13., 42.,  3., 50., 16., 82., 73., 51., 39., 58., 47., 61., 65.,
       36., 66., 43.,  9., 72., 59.,  6., 64., 23., 71., 44., 27., 62.,
       68., 63., 70., 53.,  8., 77., 74.,  5., 86., 84., 87., 75.,  1.,
       81., 78.,  2.])

In [127]:
Attack_age_fatal = attacks_fatal.loc[attacks_fatal['idade'] > 0]

In [128]:
Attack_age_fatal['idade'].shape

(3184,)

In [129]:
Attack_age_fatal.head(2)

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze,idade
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and paddle damaged",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf,2018.06.25,2018.06.25,6303.0,N,57.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,2018.06.18,2018.06.18,6302.0,N,11.0

In [164]:
Attack_age_fatal['fatal_(y/n)_ze'].unique()

array(['N', 'Y'], dtype=object)

In [166]:
Attack_age_fatal['sex_'].unique()

array(['F', 'M'], dtype=object)

In [150]:
Attack_age_fatal = Attack_age_fatal.drop('Soma_mortes', axis = 1)

In [151]:
Attack_age_fatal.loc[~(Attack_age_fatal['fatal_(y/n)_ze'] == 'Y'), 'Soma_mortes'] = 0

In [152]:
Attack_age_fatal['Soma_mortes'] = Attack_age_fatal['Soma_mortes'].fillna(1)

In [135]:
Attack_age_fatal['Soma_mortes'].unique()

array([1., 0.])

In [158]:
mpg_labels = ['0 - 20', '20 - 35', '35 - 50', '51 - 65', '65 - 100']

cutoffs = [0,20,35,50,65,100]

Attack_age_fatal['Age_group'] = pd.cut(Attack_age_fatal['idade'], cutoffs, labels=mpg_labels)

In [145]:
pd.options.display.max_columns = 99

In [159]:
Attack_age_fatal.head()

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze,idade,Soma_mortes,Age_group
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and paddle damaged",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf,2018.06.25,2018.06.25,6303.0,N,57.0,0.0,51 - 65
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,2018.06.18,2018.06.18,6302.0,N,11.0,0.0,0 - 20
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.09-Denges.pdf,2018.06.09,2018.06.09,6301.0,N,48.0,0.0,35 - 50
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.03.a-daSilva.pdf,2018.06.03.a,2018.06.03.a,6297.0,Y,18.0,1.0,0 - 20
7,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.05.27-Ponce.pdf,2018.05.27,2018.05.27,6296.0,N,52.0,0.0,51 - 65

In [172]:
Attack_age_fatal.shape

(3184, 26)

In [174]:
Attack_age_fatal.loc[Attack_age_fatal['Age_group'] == '0 - 20']

,case_number,date,year,type,country,area,location,activity,name,sex_,age,injury,fatal_(y/n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order,fatal_(y/n)_ze,idade,Soma_mortes,Age_group
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf,2018.06.18,2018.06.18,6302.0,N,11.0,0.0,0 - 20
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.03.a-daSilva.pdf,2018.06.03.a,2018.06.03.a,6297.0,Y,18.0,1.0,0 - 20
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,Lower left leg bitten,N,17h00,"Bull shark, 6'","K.McMurray, TrackingSharks.com",2018.05.26.b-High.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.05.26.b-High.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.05.26.b-High.pdf,2018.05.26.b,2018.05.26.b,6295.0,N,15.0,0.0,0 - 20
9,2018.05.26.a,26-May-2018,2018.0,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",Standing,male,M,12,Minor injury to foot,N,14h00,NaN,"K. McMurray, Tracking Sharks.com",2018.05.26.a-DaytonaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.05.26.a-DaytonaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.05.26.a-DaytonaBeach.pdf,2018.05.26.a,2018.05.26.a,6294.0,N,12.0,0.0,0 - 20
11,2018.05.21,21-May-2018,2018.0,Unprovoked,USA,South Carolina,"Isle of Palms, Charleston County",Boogie boarding,Trey de Boer,M,10,Injuries to lower right leg and foot,N,NaN,NaN,"C. Creswell, GSAF",2018.05.21-deBoer.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.05.21-deBoer.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/2018.05.21-deBoer.pdf,2018.05.21,2018.05.21,6292.0,N,10.0,0.0,0 - 20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6063,1842.00.00.b,1842,1842.0,Unprovoked,INDIA,Tamil Nadu,Chennai (formerly Madras),Washed off catamaran in the surf,male,M,8,FATAL,Y,NaN,NaN,"Tioga Eagle, 10/26/1842",1842.00.00.b-Hindoo.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1842.00.00.b-Hindoo.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1842.00.00.b-Hindoo.pdf,1842.00.00.b,1842.00.00.b,240.0,Y,8.0,1.0,0 - 20
6265,ND.0038,1941-1942,0.0,Unprovoked,IRAQ,Basrah,Shatt-el Arab River near a small boat stand,Swimming,male,M,14,"FATAL, left leg bitten with severe blood loss",Y,Afternoon,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0038-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0038-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0038-Shatt-al-Arab.pdf,ND.0038,ND.0038,38.0,Y,14.0,1.0,0 - 20
2422,1994.09.11.R,Reported 11-Sep-1994,1994.0,Sea Disaster,USA,Florida,Florida Straits,Adrift on refugee raft,2 Cuban brothers,M,7 & 31,FATAL,Y,NaN,NaN,"Sunday Herald Sun, 9/11/1994, p.25",1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1994.09.11.R-CubanRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1994.09.11.R-CubanRefugees.pdf,1994.09.11.R,1994.09.11.R,3881.0,Y,7.0,1.0,0 - 20
4801,1939.01.12,12-Jan-1939,1939.0,Unprovoked,AUSTRALIA,New South Wales,Clarence River,Scooping prawns,Earl Yager & Riley McLachlan,M,Both 11,No injury,N,NaN,7' shark,"G.P. Whitley, p.264",1939.01.12.R-ClarenceRiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1939.01.12.R-ClarenceRiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1939.01.12.R-ClarenceRiver.pdf,1939.01.12,1939.01.12,1502.0,N,11.0,0.0,0 - 20
4801,1939.01.12,12-Jan-1939,1939.0,Unprovoked,AUSTRALIA,New South Wales,Clarence River,Scooping prawns,Earl Yager & Riley McLachlan,M,Both 11,No injury,N,NaN,7' shark,"G.P. Whitley, p.264",1939.01.12.R-ClarenceRiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1939.01.12.R-ClarenceRiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_directory/1939.01.12.R-ClarenceRiver.pdf,1939.01.12,1939.01.12,1502.0,N,11.0,0.0,0 - 20

In [163]:
Attack_age_fatal.to_csv('Ataques.csv', index=False)


#attacks= pd.read_csv('attacks.csv', encoding='latin1')